WXR\GeoBundle\Entity\BaseRegion:
    type: mappedSuperclass
    fields:
        iso:
            length: 5
        abbreviation:
            length: 2
        name:
            length: 50
        latitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
        longitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
