WXR\GeoBundle\Entity\BaseCity:
    type: mappedSuperclass
    fields:
        postalCode:
            column: postal_code
            length: 10
        name:
            length: 50
        latitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
        longitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
