WXR\GeoBundle\Entity\BaseCountry:
    type: mappedSuperclass
    fields:
        iso:
            length: 2
            unique: true
        name:
            length: 50
        latitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
        longitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
