WXR\GeoBundle\Entity\City:
    type: entity
    table: wxr_geo_city
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        postalCode:
            column: postal_code
            length: 10
        name:
            length: 50
    manyToOne:
        region:
            targetEntity: Region
            inversedBy: cities
            joinColumn:
                name: region_id
                referencedColumnName: id
                onDelete: SET NULL
    oneToMany:
        addresses:
            targetEntity: Address
            mappedBy: city
