services:

    wxr_geo.region.default_manager:
        class: WXR\GeoBundle\Entity\RegionManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.region.class%]

    wxr_geo.region.form:
        factory_service: form.factory
        factory_method: create
        class: Symfony\Component\Form\Form
        arguments: [ @wxr_geo.region.form.type ]

    wxr_geo.region.form.default_type:
        class: WXR\GeoBundle\Form\Type\RegionType
        arguments: [ %wxr_geo.region.class% ]

    wxr_geo.region.form.default_handler:
        class: WXR\GeoBundle\Form\Handler\RegionHandler
        scope: request
        arguments: [ @request, @wxr_geo.region.form, @wxr_geo.region.manager ]
