wxr_geo_city_list:
    pattern: /list
    defaults: { _controller: WXRGeoBundle:City:list }

wxr_geo_city_add:
    pattern: /add
    defaults: { _controller:WXRGeoBundle:City:add }

wxr_geo_city_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRGeoBundle:City:edit }

wxr_geo_city_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRGeoBundle:City:delete }
