services:

    wxr_geo.location.default_manager:
        class: WXR\GeoBundle\Entity\LocationManager
        arguments: [@doctrine.orm.entity_manager, %wxr_geo.location.class%]

    wxr_geo.location.form:
        factory_service: form.factory
        factory_method: create
        class: Symfony\Component\Form\Form
        arguments: [ @wxr_geo.location.form.type ]

    wxr_geo.location.form.default_type:
        class: WXR\GeoBundle\Form\Type\LocationType
        arguments: [ %wxr_geo.location.class% ]

    wxr_geo.location.form.default_handler:
        class: WXR\GeoBundle\Form\Handler\LocationHandler
        scope: request
        arguments: [ @request, @wxr_geo.location.form, @wxr_geo.location.manager ]
