wxr_geo_city_admin_list:
    pattern: /list
    defaults: { _controller: WXRGeoBundle:CityAdmin:list }

wxr_geo_city_admin_add:
    pattern: /add
    defaults: { _controller:WXRGeoBundle:CityAdmin:add }

wxr_geo_city_admin_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRGeoBundle:CityAdmin:edit }

wxr_geo_city_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRGeoBundle:CityAdmin:delete }
