wxr_geo_country_admin_list:
    pattern: /list
    defaults: { _controller: WXRGeoBundle:CountryAdmin:list }

wxr_geo_country_admin_add:
    pattern: /add
    defaults: { _controller:WXRGeoBundle:CountryAdmin:add }

wxr_geo_country_admin_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRGeoBundle:CountryAdmin:edit }

wxr_geo_country_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRGeoBundle:CountryAdmin:delete }
