wxr_geo_region_admin_list:
    pattern: /list
    defaults: { _controller: WXRGeoBundle:RegionAdmin:list }

wxr_geo_region_admin_add:
    pattern: /add
    defaults: { _controller:WXRGeoBundle:RegionAdmin:add }

wxr_geo_region_admin_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRGeoBundle:RegionAdmin:edit }

wxr_geo_region_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRGeoBundle:RegionAdmin:delete }
