wxr_geo_country_list:
    pattern: /list
    defaults: { _controller: WXRGeoBundle:Country:list }

wxr_geo_country_add:
    pattern: /add
    defaults: { _controller:WXRGeoBundle:Country:add }

wxr_geo_country_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRGeoBundle:Country:edit }

wxr_geo_country_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRGeoBundle:Country:delete }
