WXR\GeoBundle\Entity\Location:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            length: 50
        street:
            length: 100
        latitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
        longitude:
            type: decimal
            precision: 8
            scale: 6
            nullable: true
    manyToOne:
        city:
            targetEntity: City
            inversedBy: locations
            joinColumn:
                name: city_id
                referencedColumnName: id
                onDelete: SET NULL
