WXR\GeoBundle\Model\Place:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        name:
            expose: true
            type: string
    virtual_properties:
        getLatitude:
            expose: true
            type: double
        getLongitude:
            expose: true
            type: double
        getAddressId:
            expose: true
            type: integer
        getAddressStreet:
            expose: true
            type: string
        getCityId:
            expose: true
            type: integer
        getRegionId:
            expose: true
            type: integer
        getRegionIso:
            expose: true
            type: string
        getRegionAbbreviation:
            expose: true
            type: string
        getRegionName:
            expose: true
            type: string
        getCountryId:
            expose: true
            type: integer
        getCountryIso:
            expose: true
            type: string
        getCountryName:
            expose: true
            type: string
